/* eslint-disable */
// @ts-nocheck
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface ListUserQuery
 */
export interface ListUserQuery {
    /**
     * 
     * @type {string}
     * @memberof ListUserQuery
     */
    query?: string | null;
}

/**
 * Check if a given object implements the ListUserQuery interface.
 */
export function instanceOfListUserQuery(value: object): value is ListUserQuery {
    return true;
}

export function ListUserQueryFromJSON(json: any): ListUserQuery {
    return ListUserQueryFromJSONTyped(json, false);
}

// @ts-ignore
export function ListUserQueryFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListUserQuery {
    if (json == null) {
        return json;
    }
    return {
        
        'query': json['query'] == null ? undefined : json['query'],
    };
}

export function ListUserQueryToJSON(json: any): ListUserQuery {
    return ListUserQueryToJSONTyped(json, false);
}

export function ListUserQueryToJSONTyped(value?: ListUserQuery | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'query': value['query'],
    };
}

