/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResetUsersRequest
 */
export interface ResetUsersRequest {
    /**
     * 
     * @type {Array<string>}
     * @memberof ResetUsersRequest
     */
    userIds: Array<string>;
}

/**
 * Check if a given object implements the ResetUsersRequest interface.
 */
export function instanceOfResetUsersRequest(value: object): value is ResetUsersRequest {
    if (!('userIds' in value) || value['userIds'] === undefined) return false;
    return true;
}

export function ResetUsersRequestFromJSON(json: any): ResetUsersRequest {
    return ResetUsersRequestFromJSONTyped(json, false);
}

export function ResetUsersRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResetUsersRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'userIds': json['user_ids'],
    };
}

export function ResetUsersRequestToJSON(json: any): ResetUsersRequest {
    return ResetUsersRequestToJSONTyped(json, false);
}

export function ResetUsersRequestToJSONTyped(value?: ResetUsersRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'user_ids': value['userIds'],
    };
}

