# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2025 Univention GmbH

---

nubusBaseUrl: "nubus.example.test"

keycloak:
  realm: "nubus"
  auth:
    password: "password"
  connection:
    # -- Keycloak URL (for the helpdesk UI).
    url: "https://id.example.test"
    # -- Keycloak host.
    host: "nubus-keycloak"
    # -- Keycloak port.
    port: "8080"

keycloakBootstrap:
  enabled: true
  config:
    debug:
      enabled: true
  resources:
    limits:
      cpu: "1"
      memory: "1Gi"
    requests:
      cpu: "100m"
      memory: "32Mi"

ingress:
  ingressClassName: "nginx"
  host: "twofa.example.test"
  tls:
    secretName: "twofa-tls"

twofaHelpdeskBackend:
  config:
    oidc_realm: "nubus"
    oidc_client: "twofa-helpdesk"
    twofa_admin_groups: ["/dummy group"]
  resources:
    limits:
      cpu: "1"
      memory: "1Gi"
    requests:
      cpu: "100m"
      memory: "32Mi"

twofaHelpdeskFrontend:
  resources:
    limits:
      cpu: "1"
      memory: "1Gi"
    requests:
      cpu: "100m"
      memory: "32Mi"

...
