
# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2025 Univention GmbH
---
include:
  - project: "univention/dev/nubus-for-k8s/common-ci"
    ref: "v1.43.3"
    file:
      - "defaults/stages.yaml"
      - "defaults/nubus-workflow.yaml"
      - "jobs/lint-pre-commit.yaml"
      - "jobs/lint-commit-messages.yaml"
      - "jobs/semantic-release-env.yaml"
      - "jobs/container-build-external.yaml"
      - "jobs/package-and-publish-helm-charts-external.yaml"
      - "templates/sonarqube.yaml"
  - project: "univention/infrastructure/docker-services"
    ref: "master"
    file:
      - "dind.yml"

.build-matrix: &build-matrix
  - IMAGE_NAME:
      - "twofa-helpdesk-backend"
      - "twofa-helpdesk-extensions"
      - "twofa-helpdesk-frontend"
  - IMAGE_NAME: "twofa-helpdesk-frontend-testrunner"
    DOCKERFILE_PATH: "docker/twofa-helpdesk-frontend/Dockerfile"
    KANIKO_BUILD_CONTEXT: "${CI_PROJECT_DIR}"
    KANIKO_ARGS: "--target=base"
  - IMAGE_NAME: "testrunner"
    DOCKERFILE_PATH: "docker/testrunner/Dockerfile"
    KANIKO_BUILD_CONTEXT: "${CI_PROJECT_DIR}/docker/testrunner"
.publish-matrix: &publish-matrix
  - IMAGE_NAME:
      - "twofa-helpdesk-backend"
      - "twofa-helpdesk-frontend"
      - "twofa-helpdesk-extensions"

container-build:
  parallel:
    matrix: *build-matrix
  variables:
    KANIKO_BUILD_CONTEXT: "$CI_PROJECT_DIR"
    DOCKERFILE_PATH: "docker/${IMAGE_NAME}/Dockerfile"

container-malware-scan:
  parallel:
    matrix: *publish-matrix
container-sign-external:
  parallel:
    matrix: *build-matrix

push-image-external:
  parallel:
    matrix: *publish-matrix


test-chart:
  stage: test
  needs: []
  image: "gitregistry.knut.univention.de/univention/dev/nubus-for-k8s/common-helm/testrunner:latest"
  script:
    - helm dep build helm/twofa-helpdesk
    - pytest -W error -v tests/chart

test-frontend-unit:
  stage: test
  image: "${CI_REGISTRY_IMAGE}/twofa-helpdesk-frontend-testrunner:${RELEASE_VERSION}"
  script:
    - cd /app
    - yarn test

test-backend:
  stage: test
  extends: ".dind"
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: "never"
    - when: "on_success"
  image: "${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/docker:27.4.1"
  before_script:
    # Allow that the Docker API version is negotiated between client and server
    - unset DOCKER_API_VERSION
    - export IMAGE_TAG=${RELEASE_VERSION}
    - echo -e "\e[0Ksection_start:`date +%s`:docker_debug[collapsed=true]\r\e[0KDocker version details"
    - echo $IMAGE_TAG
    - docker version
    - echo -e "\e[0Ksection_end:`date +%s`:docker_debug\r\e[0K"
    - echo -e "\e[0Ksection_end:`date +%s`:docker_compose_config\r\e[0K"
    - docker compose --profile test-it up --no-build --quiet-pull --wait --wait-timeout 180
  script:
    - docker compose run --quiet-pull --rm testrunner bash -c 'pytest -lvv tests/integration/api-2fa'
  after_script:
    - docker compose down --volumes

sonarqube:
  extends: .sonarqube
  needs: []
