
# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2023-2025 Univention GmbH
---
include:
  - project: "univention/customers/dataport/upx/common-ci"
    ref: "main"
    file:
      - "defaults/stages.yaml"
      - "defaults/nubus-workflow.yaml"
      - "jobs/lint-pre-commit.yaml"
      - "jobs/lint-commit-messages.yaml"
      - "jobs/semantic-release-env.yaml"
      - "jobs/container-build-external.yaml"
      - "jobs/package-and-publish-helm-charts-external.yaml"

.build-matrix: &build-matrix
  - IMAGE_NAME:
      - "twofa-helpdesk-backend"
      - "twofa-helpdesk-frontend"
      - "twofa-helpdesk-exentions"
.publish-matrix: &publish-matrix
  - IMAGE_NAME:
      - "twofa-helpdesk-backend"
container-build:
  parallel:
    matrix: *build-matrix
  variables:
    KANIKO_BUILD_CONTEXT: "$CI_PROJECT_DIR"
    DOCKERFILE_PATH: "docker/${IMAGE_NAME}/Dockerfile"

container-malware-scan:
  parallel:
    matrix: *publish-matrix
container-sign-external:
  parallel:
    matrix: *build-matrix

push-image-external:
  parallel:
    matrix: *publish-matrix

# package-helm-charts:
#   variables:
#     SKIP_UPDATE_HELM_VALUES: 1