# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2025 Univention GmbH

services:

  # Environment of the pre-commit linter.
  pre-commit:
    profiles:
      - test
    image: gitregistry.knut.univention.de/univention/customers/dataport/upx/container-pre-commit/upx-pre-commit:latest
    volumes:
      - type: bind
        source: .
        target: /code
      - type: volume
        # pre-commit installs dependencies, having them cached speeds things up
        # a lot.
        source: pre-commit-cache
        target: /cache

  test-chart:
    image: gitregistry.knut.univention.de/univention/dev/nubus-for-k8s/common-helm/testrunner:latest
    command: pytest tests/chart
    profiles:
      - test
    volumes:
      - "./helm/twofa-helpdesk/:/app/helm/twofa-helpdesk"
      - "./tests/chart:/app/tests/chart"

volumes:
  pre-commit-cache:
