# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2025 Univention GmbH

services:

  # Environment of the pre-commit linter.
  pre-commit:
    profiles:
      - test
    image: gitregistry.knut.univention.de/univention/customers/dataport/upx/container-pre-commit/upx-pre-commit:latest
    volumes:
      - type: bind
        source: .
        target: /code
      - type: volume
        # pre-commit installs dependencies, having them cached speeds things up
        # a lot.
        source: pre-commit-cache
        target: /cache

  test-chart:
    image: gitregistry.knut.univention.de/univention/dev/nubus-for-k8s/common-helm/testrunner:latest
    command: pytest tests/chart
    profiles:
      - test
    volumes:
      - "./helm/twofa-helpdesk/:/app/helm/twofa-helpdesk"
      - "./tests/chart:/app/tests/chart"

  keycloak:
    image: quay.io/keycloak/keycloak:26.3.0
    profiles:
      - test-it
    command: start-dev --import-realm
    env_file: .env.test
    healthcheck:
      test: ["CMD-SHELL", "exec 3<> /dev/tcp/127.0.0.1/9000; echo -e 'GET /health/ready HTTP/1.1\\r\\nHost: 127.0.0.1:9000\\r\\nConnection: close\\r\\n\\r\\n' >&3; cat <&3 | grep -q '200 OK' && exit 0 || exit 1"]
      start_period: 60s
      start_interval: 1s
      timeout: 5s
    volumes:
      - ./tests/twofa/realm:/opt/keycloak/data/import
    ports:
      - 8080:8080

  api:
    image: gitregistry.knut.univention.de/univention/dev/projects/2fa-helpdesk/twofa-helpdesk-backend:${IMAGE_TAG:-latest}
    profiles:
      - test-it
    env_file: .env.test
    depends_on:
      keycloak:
        condition: service_healthy
        restart: true

  testrunner:
    image: gitregistry.knut.univention.de/univention/dev/projects/2fa-helpdesk/testrunner:${IMAGE_TAG:-latest}
    profiles:
      - testrunner
    env_file: .env.test
    volumes:
      - type: bind
        source: .
        target: /app/

volumes:
  pre-commit-cache:
