# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2025 Univention GmbH

{{- if .Values.twofaHelpdeskFrontend.service.enabled }}
---

apiVersion: "v1"
kind: "Service"
metadata:
  name: {{ printf "%s-ui" (include "common.names.fullname" .) }}
  namespace: {{ include "common.names.namespace" $ }}
  labels:
    app: {{ printf "%s-ui" (include "common.names.fullname" .) }}
    {{- include "common.labels.standard" ( dict "customLabels" .Values.additionalLabels "context" . ) | nindent 4 }}
  {{- include "nubus-common.annotations.render" ( dict
    "values" ( list .Values.twofaHelpdeskFrontend.service.annotations .Values.additionalAnnotations )
    "context" . )
    | nindent 2 }}
spec:
  type: {{ .Values.twofaHelpdeskFrontend.service.type }}
  {{- if .Values.twofaHelpdeskFrontend.service.sessionAffinity.enabled }}
  sessionAffinity: "ClientIP"
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: {{ .Values.twofaHelpdeskFrontend.service.sessionAffinity.timeoutSeconds }}
  {{- end }}
  ports:
    {{- range $key, $value := .Values.twofaHelpdeskFrontend.service.ports }}
    - port: {{ $value.port }}
      targetPort: 80
      protocol: {{ $value.protocol }}
      name: {{ $key }}
      {{- if and (eq $.Values.twofaHelpdeskFrontend.service.type "NodePort") $value.nodePort }}
      nodePort: {{ $value.nodePort }}
      {{- end }}
    {{- end }}
  selector:
    app: {{ printf "%s-ui" (include "common.names.fullname" .) }}
    {{- include "common.labels.matchLabels" . | nindent 4 }}

...
{{- end }}
