{{- if .Values.twofaFrontendUi.service.enabled }}
---

apiVersion: "v1"
kind: "Service"
metadata:
  name: {{ printf "%s-ui" (include "common.names.fullname" .) }}
  namespace: {{ include "common.names.namespace" $ }}
  labels:
    {{- $commonLabels := include "common.labels.standard" . | fromYaml }}
    {{- $uiLabels := dict "app.kubernetes.io/name" (printf "%s" (include "common.names.fullname" .)) }}
    {{- $mergedLabels := merge $uiLabels $commonLabels}}
    {{- toYaml $mergedLabels | nindent 4 }}
spec:
  type: {{ .Values.twofaFrontendUi.service.type }}
  {{- if .Values.twofaFrontendUi.service.sessionAffinity.enabled }}
  sessionAffinity: "ClientIP"
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: {{ .Values.twofaFrontendUi.service.sessionAffinity.timeoutSeconds }}
  {{- end }}
  ports:
    {{- range $key, $value := .Values.twofaFrontendUi.service.ports }}
    - port: {{ $value.port }}
      targetPort: 80
      protocol: {{ $value.protocol }}
      name: {{ $key }}
      {{- if and (eq $.Values.twofaFrontendUi.service.type "NodePort") $value.nodePort }}
      nodePort: {{ $value.nodePort }}
      {{- end }}
    {{- end }}
  selector:
    {{- $commonLabels := include "common.labels.matchLabels" . | fromYaml }}
    {{- $uiLabels := dict "app.kubernetes.io/name" (printf "%s-ui" (include "common.names.fullname" .)) }}
    {{- merge $uiLabels $commonLabels | toYaml | nindent 4}}

...
{{- end }}
