apiVersion: v1
kind: Service
metadata:
  name: 2fa-helpdesk-backend
spec:
  selector:
    app: 2fa-helpdesk-backend
  ports:
    - port: 80
      targetPort: 8080

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx  # or whatever your ingress controller class is
  rules:
  - host: portal.ys-opendesk.test.rancher.falkenstein-2.potaris.de
    http:
      paths:
      - path: /2fa-backend(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: backend
            port:
              number: 80