 SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2024 Univention GmbH

---

include:
  - project: "univention/customers/dataport/upx/common-ci"
    ref: "v1.36.2"
    file:
      - "defaults/stages.yaml"
      - "defaults/nubus-workflow.yaml"
      #- "jobs/lint-pre-commit.yaml"
      #- "jobs/lint-commit-messages.yaml"
      - "jobs/semantic-release-env.yaml"
      - "jobs/container-build-external.yaml"
      - "jobs/package-and-publish-helm-charts-external.yaml"

.build-matrix: &build-matrix
  - IMAGE_NAME:
      - "guardian-init"

.publish-matrix: &publish-matrix
  - IMAGE_NAME:
      - "guardian-init"

test-chart-unit:
  stage: test
  image: "gitregistry.knut.univention.de/univention/dev/nubus-for-k8s/common-helm/testrunner:0.12.1"
  script:
    - helm dep build helm/
    #- pytest tests/helm_unit

lint-pre-commit:
  before_script:
    # Compose lint would fail without the referenced env files
    - helm repo add bitnami https://charts.bitnami.com/bitnami

container-build:
  parallel:
    matrix: *build-matrix

container-malware-scan:
  parallel:
    matrix: *publish-matrix

container-sign-external:
  parallel:
    matrix: *build-matrix

push-image-external:
  parallel:
    matrix: *build-matrix

...
